### ISSUE TITLE
Versioning when bumping Selenium WebDriver dependency

### ISSUE THREAD

**Issue by dmcneil** [darcy-framework/darcy-webdriver#66]
Talking with @jvervaec this morning, the discussion of Selenium WebDriver version bumps came up. Occasionally there is a PR for bumping the version of WebDriver that gets merged in hopes of fixing some issues a particular consumer may be having with such things as what versions of Firefox a certain WebDriver build supports. Sometimes the most recent WebDriver version is backwards compatible with a certain number of Firefox versions but other times, WebDriver cuts support for older versions of Firefox that consumers may still be using reliably.

The main issue here is that when the WebDriver dependency is bumped and merged, the `darcy-webdriver` version remains the same even though I can see that making some sense since it's SNAPSHOT'd. However, if someone was doing just fine on something like `darcy-webdriver 0.3.2-SNAPSHOT` that used `selenium-webdriver 2.50.0` but then WebDriver was bumped and `darcy-webdriver` remained `0.3.2-SNAPSHOT` they may run into issues when using the latest artifact.

In my opinion, I think that there should be some sort of `darcy-webdriver` version bump as well when the WebDriver dependency is bumped so as to avoid consumers running into possible compatibility issues that may arise unknowingly. I was taking a look at semver.org to try and get an idea of what should be bumped and my guess would be either the MINOR or PATCH version. Either way, I believe there should be a bump in there somewhere.

**Comment by alechenninger** [comment]
We should avoid bumping something that is already SNAPSHOT-ed. If you rely on a SNAPSHOT dependency, that is the risk: that something may break you overnight.

The solution I see is that every time a new version of Selenium is released, we should unsnapshot and release a new version of darcy-webdriver. While we are in 0.x versions, this will be a patch version bump. Otherwise, it should match the version bump of Selenium: if it is a minor bump, we bump minor. If it is a patch bump, we bump patch. We cannot necessarily determine that from Selenium version alone as I don't think they strictly follow semver.

Either way, if we cut a new release for each selenium version bump, we should be good:

- Consumers rely on a release version which will never change on them
- If they want SNAPSHOT, that comes with risks
- We release often so consumers can get Selenium version they want without relying on SNAPSHOT
- They can also try managing the Selenium version dependency themselves, of course this may not always work depending on Selenium API changes

If above sounds good let me know and we can close issue I think.

**Comment by dmcneil** [comment]
That all makes sense and sounds good to me.

**Comment by alechenninger** [comment]
K cool. Do @jvervaec and friends need us to do a release now?

**Comment by dmcneil** [comment]
I just spoke with @jvervaec and he said it wasn't urgent right now but just something for future so I would say we can just use the process you laid out above for the future and close this issue.

**Comment by alechenninger** [comment]
K cool, sounds good to me :)
